-- INSERT INTO "user" (name, email, role, created_at, updated_at, first_name, last_name, lang, profile_color_id, display_name, dark_mode, primary_color_id)
-- VALUES
--     ('Alice Johnson', 'alice@example.com', 'USER', NOW(), NOW(), 'Alice', 'Johnson', 'en', 1, 'Alice J.', false, 1),
--     ('Bob Smith', 'bob@example.com', 'USER', NOW(), NOW(), 'Bob', 'Smith', 'en', 1, 'Bob S.', false, 1),
--     ('Charlie Brown', 'charlie@example.com', 'ADMIN', NOW(), NOW(), 'Charlie', 'Brown', 'en', 1, 'Charlie B.', false, 1),
--     ('David Wilson', 'david@example.com', 'USER', NOW(), NOW(), 'David', 'Wilson', 'pt', 1, 'David W.', false, 1),
--     ('Eve Davis', 'eve@example.com', 'ADMIN', NOW(), NOW(), 'Eve', 'Davis', 'pt', 1, 'Eve D.', true, 1),
--     ('Frank Miller', 'frank@example.com', 'USER', NOW(), NOW(), 'Frank', 'Miller', 'en', 1, 'Frank M.', false, 1),
--     ('Grace Lee', 'grace@example.com', 'USER', NOW(), NOW(), 'Grace', 'Lee', 'en', 1, 'Grace L.', false, 1),
--     ('Hank Green', 'hank@example.com', 'USER', NOW(), NOW(), 'Hank', 'Green', 'pt', 1, 'Hank G.', true, 1),
--     ('Irene Taylor', 'irene@example.com', 'ADMIN', NOW(), NOW(), 'Irene', 'Taylor', 'en', 1, 'Irene T.', false, 1),
--     ('Jack White', 'jack@example.com', 'USER', NOW(), NOW(), 'Jack', 'White', 'pt', 1, 'Jack W.', false, 1);

DELETE FROM message;
INSERT INTO "message" (user_id, sender, subject, body, created_at, send_time, sms_reference_id, status, in_trash, api_error_code, api_error_details_json, cost, cost_currency)
VALUES
    (1, 'alice@example.com', 'Old Project Update', 'Update on the project from last year.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (1, 'alice@example.com', 'Follow Up from 2022', 'Just checking in on our conversation from 2022.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0450, 'USD'),
    (1, 'alice@example.com', '2023 Project Review', 'Here is the review of the project from 2023.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0600, 'USD'),
    (2, 'bob@example.com', 'Meeting Reminder 2022', 'Don’t forget our meeting from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', 1234567890, 'SENT', false, NULL, NULL, 0.0750, 'USD'),
    (2, 'bob@example.com', 'Lunch Invitation 2023', 'Let’s have lunch next month.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (3, 'charlie@example.com', 'Draft Message 2022', 'This is a draft message from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'DRAFTED', false, NULL, NULL, 0.0000, 'USD'),
    (4, 'dave@example.com', 'Error Notification 2022', 'There was an error sending your message in 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'FAILED', false, 500, '{"error": "Internal Server Error"}', 0.1000, 'USD'),
    (5, 'eve@example.com', 'Promotional Offer 2022', 'Check out our promotional offer from 2022!', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0250, 'USD'),
    (5, 'eve@example.com', 'Feedback Request 2023', 'We would love your feedback on our service from last year.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0400, 'USD'),
    (6, 'frank@example.com', 'Follow Up 2022', 'Just following up on our last conversation from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0300, 'USD'),
    (6, 'frank@example.com', 'Service Update 2023', 'We have updated our service terms from last year.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0600, 'USD'),
    (7, 'grace@example.com', 'Feedback Request 2022', 'We would love your feedback on our service from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0400, 'USD'),
    (8, 'hank@example.com', 'Service Update 2022', 'We have updated our service terms from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0600, 'USD'),
    (9, 'irene@example.com', 'Account Verification 2022', 'Please verify your account from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SCHEDULED', false, NULL, NULL, 0.0800, 'USD'),
    (10, 'jack@example.com', 'Subscription Confirmation 2022', 'Your subscription was confirmed in 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0900, 'USD'),
    (10, 'jack@example.com', 'Welcome Message 2022', 'Welcome to our service! This was sent in 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0700, 'USD'),
    (10, 'jack@example.com', 'Reminder 2023', 'This is a reminder for your appointment from last year.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0650, 'USD'),
    (2, 'bob@example.com', 'Project Discussion 2022', 'Let’s discuss the project details from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0550, 'USD'),
    (3, 'charlie@example.com', 'Weekly Update 2022', 'Here is your weekly update from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0450, 'USD'),
    (4, 'dave@example.com', 'Follow Up 2022', 'Following up on our last meeting from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (5, 'eve@example.com', 'New Features 2022', 'Check out the new features we added in 2022!', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0350, 'USD'),
    (6, 'frank@example.com', 'Thank You 2022', 'Thank you for your support in 2022!', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0400, 'USD'),
    (7, 'grace@example.com', 'Event Invitation 2022', 'You were invited to our event in 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0550, 'USD'),
    (8, 'hank@example.com', 'Service Feedback 2022', 'We appreciate your feedback on our service from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (9, 'irene@example.com', 'Password Reset 2022', 'Click here to reset your password from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0700, 'USD'),
    (10, 'jack@example.com', 'Follow Up 2022', 'Just following up on your last inquiry from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0800, 'USD'),
    (1, 'alice@example.com', 'Daily Check-in 2023', 'How is everything going today? This was sent in 2023.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0550, 'USD'),
    (1, 'alice@example.com', 'Team Meeting 2023', 'Reminder for the team meeting at 3 PM from last year.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0650, 'USD'),
    (2, 'bob@example.com', 'Follow Up on Proposal 2022', 'Any updates on the proposal I sent in 2022?', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0450, 'USD'),
    (2, 'bob@example.com', 'Client Feedback 2023', 'Received feedback from the client in 2023.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (3, 'charlie@example.com', 'Monthly Report 2022', 'Here is the monthly report from 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0600, 'USD'),
    (3, 'charlie@example.com', 'Quarterly Review 2023', 'Here is the quarterly review from 2023.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0650, 'USD'),
    (4, 'dave@example.com', 'Budget Review 2022', 'Time to review the budget for 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0750, 'USD'),
    (4, 'dave@example.com', 'Follow Up on Budget 2023', 'Following up on the budget discussion from 2023.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0800, 'USD'),
    (5, 'eve@example.com', 'New Year Greetings 2023', 'Wishing you a Happy New Year in 2023!', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SENT', false, NULL, NULL, 0.0250, 'USD'),
    (5, 'eve@example.com', 'Holiday Reminder 2022', 'Reminder for the upcoming holiday in 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0400, 'USD'),
    (6, 'frank@example.com', 'Service Upgrade 2022', 'We are upgrading our services next month in 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SCHEDULED', false, NULL, NULL, 0.0600, 'USD'),
    (6, 'frank@example.com', 'Feedback Follow-up 2023', 'Following up on your feedback from 2023.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SCHEDULED', false, NULL, NULL, 0.0300, 'USD'),
    (7, 'grace@example.com', 'Event Reminder 2022', 'Reminder for the upcoming event in 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0550, 'USD'),
    (7, 'grace@example.com', 'Networking Event 2023', 'Join us for a networking event in 2023.', NOW() - INTERVAL '1 year', NOW() - INTERVAL '1 year', NULL, 'SCHEDULED', false, NULL, NULL, 0.0600, 'USD'),
    (8, 'hank@example.com', 'Webinar Invitation 2022', 'You are invited to our webinar in 2022.', NOW() - INTERVAL '2 years', NOW() - INTERVAL '2 years', NULL, 'SENT', false, NULL, NULL, 0.0700, 'USD'),
    (1, 'alice@example.com', 'Old Project Update', 'Update on the project from last year.', NOW() - INTERVAL '1 year 3 months', NOW() - INTERVAL '1 year 3 months', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (1, 'alice@example.com', 'Follow Up from 2022', 'Just checking in on our conversation from 2022.', NOW() - INTERVAL '1 year 6 months', NOW() - INTERVAL '1 year 6 months', NULL, 'SENT', false, NULL, NULL, 0.0450, 'USD'),
    (1, 'alice@example.com', '2023 Project Review', 'Here is the review of the project from 2023.', NOW() - INTERVAL '8 months', NOW() - INTERVAL '8 months', NULL, 'SENT', false, NULL, NULL, 0.0600, 'USD'),
    (2, 'bob@example.com', 'Meeting Reminder 2022', 'Don’t forget our meeting from 2022.', NOW() - INTERVAL '1 year 9 months', NOW() - INTERVAL '1 year 9 months', 1234567890, 'SENT', false, NULL, NULL, 0.0750, 'USD'),
    (2, 'bob@example.com', 'Lunch Invitation 2023', 'Let’s have lunch next month.', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (3, 'charlie@example.com', 'Draft Message 2022', 'This is a draft message from 2022.', NOW() - INTERVAL '1 year 5 months', NOW() - INTERVAL '1 year 5 months', NULL, 'DRAFTED', false, NULL, NULL, 0.0000, 'USD'),
    (4, 'dave@example.com', 'Error Notification 2022', 'There was an error sending your message in 2022.', NOW() - INTERVAL '1 year 8 months', NOW() - INTERVAL '1 year 8 months', NULL, 'FAILED', false, 500, '{"error": "Internal Server Error"}', 0.1000, 'USD'),
    (5, 'eve@example.com', 'Promotional Offer 2022', 'Check out our promotional offer from 2022!', NOW() - INTERVAL '1 year 10 months', NOW() - INTERVAL '1 year 10 months', NULL, 'SENT', false, NULL, NULL, 0.0250, 'USD'),
    (5, 'eve@example.com', 'Feedback Request 2023', 'We would love your feedback on our service from last year.', NOW() - INTERVAL '2 months', NOW() - INTERVAL '2 months', NULL, 'SENT', false, NULL, NULL, 0.0400, 'USD'),
    (6, 'frank@example.com', 'Follow Up 2022', 'Just following up on our last conversation from 2022.', NOW() - INTERVAL '1 year 7 months', NOW() - INTERVAL '1 year 7 months', NULL, 'SENT', false, NULL, NULL, 0.0300, 'USD'),
    (6, 'frank@example.com', 'Service Update 2023', 'We have updated our service terms from last year.', NOW() - INTERVAL '3 months', NOW() - INTERVAL '3 months', NULL, 'SENT', false, NULL, NULL, 0.0600, 'USD'),
    (7, 'grace@example.com', 'Feedback Request 2022', 'We would love your feedback on our service from 2022.', NOW() - INTERVAL '1 year 11 months', NOW() - INTERVAL '1 year 11 months', NULL, 'SENT', false, NULL, NULL, 0.0400, 'USD'),
    (8, 'hank@example.com', 'Service Update 2022', 'We have updated our service terms from 2022.', NOW() - INTERVAL '1 year 9 months', NOW() - INTERVAL '1 year 9 months', NULL, 'SENT', false, NULL, NULL, 0.0600, 'USD'),
    (9, 'irene@example.com', 'Account Verification 2022', 'Please verify your account from 2022.', NOW() - INTERVAL '1 year 8 months', NOW() - INTERVAL '1 year 8 months', NULL, 'SCHEDULED', false, NULL, NULL, 0.0800, 'USD'),
    (10, 'jack@example.com', 'Subscription Confirmation 2022', 'Your subscription was confirmed in 2022.', NOW() - INTERVAL '1 year 10 months', NOW() - INTERVAL '1 year 10 months', NULL, 'SENT', false, NULL, NULL, 0.0900, 'USD'),
    (10, 'jack@example.com', 'Welcome Message 2022', 'Welcome to our service! This was sent in 2022.', NOW() - INTERVAL '1 year 11 months', NOW() - INTERVAL '1 year 11 months', NULL, 'SENT', false, NULL, NULL, 0.0700, 'USD'),
    (10, 'jack@example.com', 'Reminder 2023', 'This is a reminder for your appointment from last year.', NOW() - INTERVAL '5 months', NOW() - INTERVAL '5 months', NULL, 'SENT', false, NULL, NULL, 0.0650, 'USD'),
    (2, 'bob@example.com', 'Project Discussion 2022', 'Let’s discuss the project details from 2022.', NOW() - INTERVAL '1 year 6 months', NOW() - INTERVAL '1 year 6 months', NULL, 'SENT', false, NULL, NULL, 0.0550, 'USD'),
    (3, 'charlie@example.com', 'Weekly Update 2022', 'Here is your weekly update from 2022.', NOW() - INTERVAL '1 year 7 months', NOW() - INTERVAL '1 year 7 months', NULL, 'SENT', false, NULL, NULL, 0.0450, 'USD'),
    (4, 'dave@example.com', 'Follow Up 2022', 'Following up on our last meeting from 2022.', NOW() - INTERVAL '1 year 5 months', NOW() - INTERVAL '1 year 5 months', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (5, 'eve@example.com', 'New Features 2022', 'Check out the new features we added in 2022!', NOW() - INTERVAL '1 year 4 months', NOW() - INTERVAL '1 year 4 months', NULL, 'SENT', false, NULL, NULL, 0.0350, 'USD'),
    (6, 'frank@example.com', 'Thank You 2022', 'Thank you for your support in 2022!', NOW() - INTERVAL '1 year 3 months', NOW() - INTERVAL '1 year 3 months', NULL, 'SENT', false, NULL, NULL, 0.0400, 'USD'),
    (7, 'grace@example.com', 'Event Invitation 2022', 'You were invited to our event in 2022.', NOW() - INTERVAL '1 year 2 months', NOW() - INTERVAL '1 year 2 months', NULL, 'SENT', false, NULL, NULL, 0.0550, 'USD'),
    (8, 'hank@example.com', 'Service Feedback 2022', 'We appreciate your feedback on our service from 2022.', NOW() - INTERVAL '1 year 1 month', NOW() - INTERVAL '1 year 1 month', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (9, 'irene@example.com', 'Password Reset 2022', 'Click here to reset your password from 2022.', NOW() - INTERVAL '1 year 10 months', NOW() - INTERVAL '1 year 10 months', NULL, 'SENT', false, NULL, NULL, 0.0700, 'USD'),
    (10, 'jack@example.com', 'Follow Up 2022', 'Just following up on your last inquiry from 2022.', NOW() - INTERVAL '1 year 9 months', NOW() - INTERVAL '1 year 9 months', NULL, 'SENT', false, NULL, NULL, 0.0800, 'USD'),
    (1, 'alice@example.com', 'Daily Check-in 2023', 'How is everything going today? This was sent in 2023.', NOW() - INTERVAL '6 months', NOW() - INTERVAL '6 months', NULL, 'SENT', false, NULL, NULL, 0.0550, 'USD'),
    (1, 'alice@example.com', 'Team Meeting 2023', 'Reminder for the team meeting at 3 PM from last year.', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months', NULL, 'SENT', false, NULL, NULL, 0.0650, 'USD'),
    (2, 'bob@example.com', 'Follow Up on Proposal 2022', 'Any updates on the proposal I sent in 2022?', NOW() - INTERVAL '1 year 8 months', NOW() - INTERVAL '1 year 8 months', NULL, 'SENT', false, NULL, NULL, 0.0450, 'USD'),
    (2, 'bob@example.com', 'Client Feedback 2023', 'Received feedback from the client in 2023.', NOW() - INTERVAL '3 months', NOW() - INTERVAL '3 months', NULL, 'SENT', false, NULL, NULL, 0.0500, 'USD'),
    (3, 'charlie@example.com', 'Monthly Report 2022', 'Here is the monthly report from 2022.', NOW() - INTERVAL '1 year 7 months', NOW() - INTERVAL '1 year 7 months', NULL, 'SENT', false, NULL, NULL, 0.0600, 'USD'),
    (3, 'charlie@example.com', 'Quarterly Review 2023', 'Here is the quarterly review from 2023.', NOW() - INTERVAL '2 months', NOW() - INTERVAL '2 months', NULL, 'SENT', false, NULL, NULL, 0.0650, 'USD'),
    (4, 'dave@example.com', 'Budget Review 2022', 'Time to review the budget for 2022.', NOW() - INTERVAL '1 year 5 months', NOW() - INTERVAL '1 year 5 months', NULL, 'SENT', false, NULL, NULL, 0.0750, 'USD'),
    (4, 'dave@example.com', 'Follow Up on Budget 2023', 'Following up on the budget discussion from 2023.', NOW() - INTERVAL '1 month', NOW() - INTERVAL '1 month', NULL, 'SENT', false, NULL, NULL, 0.0800, 'USD'),
    (5, 'eve@example.com', 'New Year Greetings 2023', 'Wishing you a Happy New Year in 2023!', NOW() - INTERVAL '2 months', NOW() - INTERVAL '2 months', NULL, 'SENT', false, NULL, NULL, 0.0250, 'USD'),
    (5, 'eve@example.com', 'Holiday Reminder 2022', 'Reminder for the upcoming holiday in 2022.', NOW() - INTERVAL '1 year 10 months', NOW() - INTERVAL '1 year 10 months', NULL, 'SENT', false, NULL, NULL, 0.0400, 'USD'),
    (6, 'frank@example.com', 'Service Upgrade 2022', 'We are upgrading our services next month in 2022.', NOW() - INTERVAL '1 year 9 months', NOW() - INTERVAL '1 year 9 months', NULL, 'SCHEDULED', false, NULL, NULL, 0.0600, 'USD'),
    (6, 'frank@example.com', 'Feedback Follow-up 2023', 'Following up on your feedback from 2023.', NOW() - INTERVAL '1 month', NOW() - INTERVAL '1 month', NULL, 'SCHEDULED', false, NULL, NULL, 0.0300, 'USD');
