import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LanguageChanger from "@/app/components/LanguageChanger";
import { i18nConfig } from "@/i18nConfig";
import { dir } from "i18next";
import TranslationsProvider from "../providers/TranslationsProvider";
import initTranslations from "../i18n";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const i18Namespaces = ["Home", "Common"];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

type RootLayoutProps = {
  children: React.ReactNode;
  params: { locale: string };
};

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = await params;
  const { resources } = await initTranslations(locale, i18Namespaces);
  return (
    <TranslationsProvider
      resources={resources}
      locale={locale}
      namespaces={i18Namespaces}
    >
      <html lang={locale} dir={dir(locale)}>
        {/* <head></head> */}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
        >
          <header className="flex justify-between items-center py-[10px] px-[15px] bg-slate-100">
            HEADER
            <LanguageChanger />
          </header>
          {children}

          <footer>FOOTER</footer>
        </body>
      </html>
    </TranslationsProvider>
  );
}
